# Generated by Django 5.0.4 on 2024-04-09 19:05

import Accounts.custom_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStockTake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created', models.DateTimeField(auto_now_add=True)),
                ('record_updated', models.DateTimeField(auto_now=True)),
                ('grand_held_opening_stock', models.PositiveIntegerField(default=0)),
                ('grand_held_closing_stock', models.PositiveIntegerField(default=0)),
                ('grand_units_transferred_since_st', models.PositiveIntegerField(default=0)),
                ('grand_units_recorded_sold_since_st', models.PositiveIntegerField(default=0)),
                ('grand_units_recorded_shrunk_since_st', models.PositiveIntegerField(default=0)),
                ('grand_units_unrecorded_hist_diff_since_st', models.IntegerField(default=0)),
                ('grand_total_value_recorded_sold_since_st', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('grand_total_value_recorded_shrunk_since_st', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('grand_total_value_unrecorded_current_xfer_price_since_st', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('grand_total_value_unrecorded_current_retail_price_since_st', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('grand_total_xferred_value_since_last_stock_take', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('grand_held_stock_value_at_current_xfer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('grand_held_stock_value_at_present_retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('grand_all_time_total_at_actual_xfer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_stock_take', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner',),
            },
        ),
        migrations.CreateModel(
            name='AccountStockTakeLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_line', models.CharField(max_length=100, validators=[Accounts.custom_validators.validate_alphanumplus])),
                ('stock_desc', models.CharField(max_length=100, validators=[Accounts.custom_validators.validate_alphanumplus])),
                ('xfer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('opening_stock', models.PositiveIntegerField(default=0)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('units_diff', models.IntegerField(default=0)),
                ('units_xferred', models.PositiveIntegerField(default=0)),
                ('units_sold', models.PositiveIntegerField(default=0)),
                ('units_shrunk', models.PositiveIntegerField(default=0)),
                ('unrecorded', models.IntegerField(default=0)),
                ('sold_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('shrinkage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('xferred_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('unrecorded_xfer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('unrecorded_retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('held_stock_current_xfer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('held_stock_retail_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_take', related_query_name='stock_take_lines', to='Accounts.accountstocktake')),
            ],
            options={
                'ordering': ('stock_take',),
            },
        ),
        migrations.CreateModel(
            name='AccountData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created', models.DateTimeField(auto_now_add=True)),
                ('record_updated', models.DateTimeField(auto_now=True)),
                ('all_time_total_xfer_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_meta_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('owner',),
                'indexes': [models.Index(fields=['owner', 'all_time_total_xfer_value'], name='Accounts_ac_owner_i_bb75b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountStockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created', models.DateTimeField(auto_now_add=True)),
                ('record_updated', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, validators=[Accounts.custom_validators.validate_alphanumplus])),
                ('desc', models.CharField(blank=True, max_length=100, validators=[Accounts.custom_validators.validate_alphanumplus])),
                ('units_total', models.PositiveIntegerField(default=0)),
                ('xferred_units', models.PositiveIntegerField(default=0)),
                ('sold_units', models.PositiveIntegerField(default=0)),
                ('shrinkage', models.PositiveIntegerField(default=0)),
                ('xfer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('opening_stock', models.PositiveIntegerField(default=0)),
                ('running_total_xfer_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('running_total_sold_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('running_total_shrinkage_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('all_time_total_xfer_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_stock_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['owner', 'desc', 'sku'], name='Accounts_ac_owner_i_a0ca67_idx')],
                'unique_together': {('sku', 'owner')},
            },
        ),
        migrations.AddIndex(
            model_name='accountstocktake',
            index=models.Index(fields=['owner'], name='Accounts_ac_owner_i_d19eae_idx'),
        ),
        migrations.AddIndex(
            model_name='accountstocktakelines',
            index=models.Index(fields=['stock_line', 'stock_desc'], name='Accounts_ac_stock_l_e454b5_idx'),
        ),
    ]
