# Generated by Django 5.0.4 on 2024-04-09 19:05

import IMS_Control.custom_validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created', models.DateTimeField(auto_now_add=True)),
                ('record_updated', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=100, unique=True, validators=[IMS_Control.custom_validators.validate_alphanumplus])),
                ('desc', models.CharField(blank=True, max_length=100, validators=[IMS_Control.custom_validators.validate_alphanumplus])),
                ('units_total', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'indexes': [models.Index(fields=['desc'], name='IMS_Control_desc_feef7e_idx'), models.Index(fields=['sku'], name='IMS_Control_sku_8e4ffe_idx')],
            },
        ),
    ]
